-- 1. Add Einstein Badge
INSERT INTO badges (name, description, icon) VALUES
('Einstein', 'Fizik dehası! 50 soru çözdün.', '🧠')
ON CONFLICT (name) DO NOTHING;

-- 2. Article Engagement (Likes & Comments)
CREATE TABLE IF NOT EXISTS article_likes (
    id BIGSERIAL PRIMARY KEY,
    article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(article_id, user_id)
);

CREATE TABLE IF NOT EXISTS article_comments (
    id BIGSERIAL PRIMARY KEY,
    article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    parent_comment_id BIGINT REFERENCES article_comments(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_article_likes_article ON article_likes(article_id);
CREATE INDEX IF NOT EXISTS idx_article_likes_user ON article_likes(user_id);
CREATE INDEX IF NOT EXISTS idx_article_comments_article ON article_comments(article_id);
CREATE INDEX IF NOT EXISTS idx_article_comments_parent ON article_comments(parent_comment_id);

ALTER TABLE article_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE article_comments ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid errors
DROP POLICY IF EXISTS "Anyone can view likes" ON article_likes;
DROP POLICY IF EXISTS "Users can like articles" ON article_likes;
DROP POLICY IF EXISTS "Users can unlike articles" ON article_likes;

DROP POLICY IF EXISTS "Anyone can view comments" ON article_comments;
DROP POLICY IF EXISTS "Users can create comments" ON article_comments;
DROP POLICY IF EXISTS "Users can delete own comments" ON article_comments;

CREATE POLICY "Anyone can view likes" ON article_likes FOR SELECT USING (true);
CREATE POLICY "Users can like articles" ON article_likes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can unlike articles" ON article_likes FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Anyone can view comments" ON article_comments FOR SELECT USING (true);
CREATE POLICY "Users can create comments" ON article_comments FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own comments" ON article_comments FOR DELETE USING (auth.uid() = user_id);

-- 3. Forum Enhancements
ALTER TABLE questions ADD COLUMN IF NOT EXISTS votes INTEGER DEFAULT 0;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';
ALTER TABLE answers ADD COLUMN IF NOT EXISTS is_accepted BOOLEAN DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS question_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    vote_type INTEGER NOT NULL CHECK (vote_type IN (1, -1)),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(question_id, user_id)
);

ALTER TABLE question_votes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view votes" ON question_votes;
DROP POLICY IF EXISTS "Authenticated users can vote" ON question_votes;
DROP POLICY IF EXISTS "Users can update own vote" ON question_votes;
DROP POLICY IF EXISTS "Users can delete own vote" ON question_votes;

CREATE POLICY "Anyone can view votes" ON question_votes FOR SELECT USING (true);
CREATE POLICY "Authenticated users can vote" ON question_votes FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own vote" ON question_votes FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own vote" ON question_votes FOR DELETE USING (auth.uid() = user_id);

-- 4. Dictionary Terms
CREATE TABLE IF NOT EXISTS dictionary_terms (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    term TEXT NOT NULL UNIQUE,
    definition TEXT NOT NULL,
    category TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

ALTER TABLE dictionary_terms ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Sözlük terimleri herkese açık" ON dictionary_terms;
DROP POLICY IF EXISTS "Sadece adminler sözlük terimi ekleyebilir" ON dictionary_terms;
DROP POLICY IF EXISTS "Sadece adminler sözlük terimi güncelleyebilir" ON dictionary_terms;
DROP POLICY IF EXISTS "Sadece adminler sözlük terimi silebilir" ON dictionary_terms;

CREATE POLICY "Sözlük terimleri herkese açık" ON dictionary_terms FOR SELECT USING (true);
CREATE POLICY "Sadece adminler sözlük terimi ekleyebilir" ON dictionary_terms FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin')
);

INSERT INTO dictionary_terms (term, definition, category, created_at) VALUES
('Karanlık Madde', 'Evrenin yaklaşık %27''sini oluşturan ancak ışık yaymadığı için doğrudan gözlemlenemeyen gizemli madde türü. Varlığını sadece kütleçekimsel etkileriyle biliyoruz. Evrenin görünmez iskeleti! 🌌', 'Astrofizik', NOW()),
('Doppler Etkisi', 'Dalga kaynağının hareketine bağlı olarak frekansın değişmesi olayı. Ambulans size yaklaşırken sesi tiz, uzaklaşırken bas duyulur. Evrenin genişlediğini de bu sayede (Kızıla Kayma) anladık! 🚑', 'Dalga Mekaniği', NOW()),
('Schrödinger''in Kedisi', 'Kuantum süperpozisyonunu açıklamak için kurgulanan ünlü düşünce deneyi. Kutu açılana kadar kedi hem ölü hem canlıdır. Merak kediyi öldürür mü? Kuantum dünyasında emin değiliz! 🐱', 'Kuantum Fiziği', NOW())
ON CONFLICT (term) DO NOTHING;
