-- Achievements/Badges System
-- Gamification for user engagement

-- ==========================================
-- BADGES TABLE
-- ==========================================

CREATE TABLE IF NOT EXISTS badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL,
    icon TEXT NOT NULL, -- Emoji or icon name
    category TEXT NOT NULL, -- 'engagement', 'contribution', 'milestone', 'special'
    requirement_type TEXT NOT NULL, -- 'question_count', 'answer_count', 'likes_received', 'best_answer', 'custom'
    requirement_value INTEGER, -- Threshold value
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- USER_BADGES TABLE (Many-to-Many)
-- ==========================================

CREATE TABLE IF NOT EXISTS user_badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    badge_id BIGINT REFERENCES badges(id) ON DELETE CASCADE NOT NULL,
    awarded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, badge_id)
);

-- ==========================================
-- BOOKMARKS TABLE
-- ==========================================

CREATE TABLE IF NOT EXISTS article_bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    article_id BIGINT REFERENCES articles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, article_id)
);

CREATE TABLE IF NOT EXISTS question_bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, question_id)
);

-- ==========================================
-- RLS POLICIES
-- ==========================================

-- Badges are publicly viewable
ALTER TABLE badges ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Badges are viewable by everyone" ON badges FOR SELECT USING (true);

-- User badges
ALTER TABLE user_badges ENABLE ROW LEVEL SECURITY;
CREATE POLICY "User badges are viewable by everyone" ON user_badges FOR SELECT USING (true);
CREATE POLICY "Admins can award badges" ON user_badges FOR INSERT 
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE id = auth.uid() 
            AND email = 'barannnbozkurttb.b@gmail.com'
        )
    );

-- Article bookmarks
ALTER TABLE article_bookmarks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own bookmarks" ON article_bookmarks FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create own bookmarks" ON article_bookmarks FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own bookmarks" ON article_bookmarks FOR DELETE USING (auth.uid() = user_id);

-- Question bookmarks
ALTER TABLE question_bookmarks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own question bookmarks" ON question_bookmarks FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can create own question bookmarks" ON question_bookmarks FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own question bookmarks" ON question_bookmarks FOR DELETE USING (auth.uid() = user_id);

-- ==========================================
-- SEED INITIAL BADGES
-- ==========================================

INSERT INTO badges (name, description, icon, category, requirement_type, requirement_value) VALUES
('İlk Adım', 'İlk sorunuzu sordunuz!', '🎯', 'milestone', 'question_count', 1),
('Meraklı', '10 soru sordunuz', '🔍', 'engagement', 'question_count', 10),
('Soru Ustası', '50 soru sordunuz', '🎓', 'engagement', 'question_count', 50),
('Yardımsever', 'İlk cevabınızı verdiniz', '💡', 'milestone', 'answer_count', 1),
('Bilge', '10 cevap verdiniz', '📚', 'contribution', 'answer_count', 10),
('Uzman', '50 cevap verdiniz', '⭐', 'contribution', 'answer_count', 50),
('Popüler', '100 beğeni aldınız', '❤️', 'engagement', 'likes_received', 100),
('Sevilen', '500 beğeni aldınız', '🔥', 'engagement', 'likes_received', 500),
('En İyi Cevap', 'Cevabınız kabul edildi', '✅', 'special', 'best_answer', 1),
('Fizik Dehası', '10 kabul edilen cevap', '🏆', 'special', 'best_answer', 10)
ON CONFLICT (name) DO NOTHING;

-- ==========================================
-- INDEXES
-- ==========================================

CREATE INDEX IF NOT EXISTS idx_user_badges_user ON user_badges(user_id);
CREATE INDEX IF NOT EXISTS idx_article_bookmarks_user ON article_bookmarks(user_id);
CREATE INDEX IF NOT EXISTS idx_question_bookmarks_user ON question_bookmarks(user_id);

-- ==========================================
-- GRANT PERMISSIONS
-- ==========================================

GRANT ALL ON badges TO authenticated;
GRANT SELECT ON badges TO anon;
GRANT ALL ON user_badges TO authenticated;
GRANT SELECT ON user_badges TO anon;
GRANT ALL ON article_bookmarks TO authenticated;
GRANT ALL ON question_bookmarks TO authenticated;
