-- Drop table if exists to ensure clean slate (WARNING: This deletes existing notifications)
drop table if not exists public.notifications cascade;

-- Create notifications table
create table public.notifications (
    id bigint generated by default as identity primary key,
    recipient_id uuid references auth.users(id) on delete cascade not null,
    actor_id uuid references auth.users(id) on delete cascade not null,
    type text not null check (type in ('like', 'comment', 'follow', 'reply', 'welcome')),
    resource_id text, -- ID of the related resource (question_id, answer_id, etc.)
    resource_type text, -- 'question', 'answer', 'profile', 'article'
    content text, -- Optional preview text
    is_read boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.notifications enable row level security;

-- Policies
create policy "Users can view their own notifications"
    on public.notifications for select
    using (auth.uid() = recipient_id);

create policy "Users can update their own notifications (mark as read)"
    on public.notifications for update
    using (auth.uid() = recipient_id);

-- System/Server actions can insert notifications (usually via service role or security definer functions)
-- But for now, we'll allow authenticated users to insert if they are the actor (e.g. when liking)
create policy "Users can insert notifications"
    on public.notifications for insert
    with check (auth.uid() = actor_id);

-- Create index for performance
create index if not exists notifications_recipient_id_idx on public.notifications(recipient_id);
create index if not exists notifications_created_at_idx on public.notifications(created_at desc);
