-- Forum Enhancements Schema

-- 1. Add votes and tags to questions
ALTER TABLE questions 
ADD COLUMN IF NOT EXISTS votes INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';

-- 2. Add is_accepted to answers
ALTER TABLE answers 
ADD COLUMN IF NOT EXISTS is_accepted BOOLEAN DEFAULT FALSE;

-- 3. Create question_votes table
CREATE TABLE IF NOT EXISTS question_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    vote_type INTEGER NOT NULL CHECK (vote_type IN (1, -1)), -- 1 for upvote, -1 for downvote
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(question_id, user_id)
);

-- 4. RLS Policies for question_votes

-- Enable RLS
ALTER TABLE question_votes ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can view votes
CREATE POLICY "Anyone can view votes" 
ON question_votes FOR SELECT 
USING (true);

-- Policy: Authenticated users can vote
CREATE POLICY "Authenticated users can vote" 
ON question_votes FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own vote
CREATE POLICY "Users can update own vote" 
ON question_votes FOR UPDATE 
USING (auth.uid() = user_id);

-- Policy: Users can delete their own vote
CREATE POLICY "Users can delete own vote" 
ON question_votes FOR DELETE 
USING (auth.uid() = user_id);

-- 5. RLS Policy for updating answers (to mark as accepted)
-- Only the question owner should be able to mark an answer as accepted
-- This is complex to enforce via simple RLS on answers table because it depends on the question owner.
-- We will handle the permission check in the Server Action for security.
-- But we need to allow updates to the answers table for the 'is_accepted' column.

CREATE POLICY "Question owners can accept answers"
ON answers FOR UPDATE
USING (
    EXISTS (
        SELECT 1 FROM questions
        WHERE questions.id = answers.question_id
        AND questions.user_id = auth.uid()
    )
);
