-- Report/Flag System & Reputation System
-- Content moderation and user gamification

-- ==========================================
-- REPORTS TABLE (Flag/Report System)
-- ==========================================

CREATE TABLE IF NOT EXISTS reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
    content_type TEXT NOT NULL, -- 'question', 'answer', 'article', 'comment'
    content_id BIGINT NOT NULL,
    reason TEXT NOT NULL, -- 'spam', 'offensive', 'misinformation', 'duplicate', 'other'
    description TEXT,
    status TEXT NOT NULL DEFAULT 'pending', -- 'pending', 'reviewed', 'resolved', 'dismissed'
    reviewed_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- REPUTATION SYSTEM
-- ==========================================

-- Add reputation column to profiles if not exists
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS reputation INTEGER DEFAULT 0;

-- Reputation history table
CREATE TABLE IF NOT EXISTS reputation_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    points INTEGER NOT NULL, -- Can be positive or negative
    reason TEXT NOT NULL, -- 'question_upvote', 'answer_accepted', 'answer_upvote', etc.
    reference_type TEXT, -- 'question', 'answer', 'article'
    reference_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- RLS POLICIES
-- ==========================================

-- Reports
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own reports" ON reports 
    FOR SELECT USING (auth.uid() = reporter_id);

CREATE POLICY "Users can create reports" ON reports 
    FOR INSERT WITH CHECK (auth.uid() = reporter_id);

CREATE POLICY "Admins can view all reports" ON reports 
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE id = auth.uid() 
            AND email = 'barannnbozkurttb.b@gmail.com'
        )
    );

CREATE POLICY "Admins can update reports" ON reports 
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM profiles 
            WHERE id = auth.uid() 
            AND email = 'barannnbozkurttb.b@gmail.com'
        )
    );

-- Reputation History
ALTER TABLE reputation_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own reputation history" ON reputation_history 
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "System can insert reputation changes" ON reputation_history 
    FOR INSERT WITH CHECK (true);

-- ==========================================
-- REPUTATION FUNCTIONS
-- ==========================================

-- Function to add reputation
CREATE OR REPLACE FUNCTION add_reputation(
    p_user_id UUID,
    p_points INTEGER,
    p_reason TEXT,
    p_reference_type TEXT DEFAULT NULL,
    p_reference_id BIGINT DEFAULT NULL
)
RETURNS void AS $$
BEGIN
    -- Update user's total reputation
    UPDATE profiles 
    SET reputation = reputation + p_points 
    WHERE id = p_user_id;
    
    -- Record in history
    INSERT INTO reputation_history (user_id, points, reason, reference_type, reference_id)
    VALUES (p_user_id, p_points, p_reason, p_reference_type, p_reference_id);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ==========================================
-- TRIGGERS FOR AUTOMATIC REPUTATION
-- ==========================================

-- When answer is accepted
CREATE OR REPLACE FUNCTION award_reputation_for_accepted_answer()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.is_accepted = true AND (OLD.is_accepted IS NULL OR OLD.is_accepted = false) THEN
        PERFORM add_reputation(NEW.author_id, 15, 'answer_accepted', 'answer', NEW.id);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_accepted_answer_reputation ON answers;
CREATE TRIGGER trigger_accepted_answer_reputation
    AFTER UPDATE ON answers
    FOR EACH ROW
    EXECUTE FUNCTION award_reputation_for_accepted_answer();

-- ==========================================
-- INDEXES
-- ==========================================

CREATE INDEX IF NOT EXISTS idx_reports_status ON reports(status);
CREATE INDEX IF NOT EXISTS idx_reports_content ON reports(content_type, content_id);
CREATE INDEX IF NOT EXISTS idx_reputation_history_user ON reputation_history(user_id);
CREATE INDEX IF NOT EXISTS idx_profiles_reputation ON profiles(reputation DESC);

-- ==========================================
-- GRANT PERMISSIONS
-- ==========================================

GRANT ALL ON reports TO authenticated;
GRANT ALL ON reputation_history TO authenticated;
GRANT EXECUTE ON FUNCTION add_reputation(UUID, INTEGER, TEXT, TEXT, BIGINT) TO authenticated;
