-- Create answer_comments table
CREATE TABLE IF NOT EXISTS answer_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    answer_id BIGINT REFERENCES answers(id) ON DELETE CASCADE NOT NULL,
    author_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE answer_comments ENABLE ROW LEVEL SECURITY;

-- Policies

-- 1. VIEW: Everyone can see comments
CREATE POLICY "Comments are viewable by everyone" 
ON answer_comments FOR SELECT 
USING (true);

-- 2. INSERT: Authenticated users can comment
CREATE POLICY "Authenticated users can comment" 
ON answer_comments FOR INSERT 
WITH CHECK (auth.uid() = author_id);

-- 3. DELETE: Users can delete their own comments
CREATE POLICY "Users can delete own comments" 
ON answer_comments FOR DELETE 
USING (auth.uid() = author_id);

-- 4. UPDATE: Users can update their own comments (optional, but good to have)
CREATE POLICY "Users can update own comments" 
ON answer_comments FOR UPDATE 
USING (auth.uid() = author_id);

-- Grant permissions
GRANT ALL ON answer_comments TO authenticated;
GRANT SELECT ON answer_comments TO anon;

-- Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE answer_comments;
