-- Create reports table
create table if not exists reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid references profiles(id) on delete cascade not null,
  resource_id text not null,
  resource_type text not null check (resource_type in ('question', 'answer', 'comment', 'user')),
  reason text not null,
  description text,
  status text not null default 'pending' check (status in ('pending', 'resolved', 'dismissed')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table reports enable row level security;

-- Policies
create policy "Users can create reports"
  on reports for insert
  with check (auth.uid() = reporter_id);

create policy "Admins can view all reports"
  on reports for select
  using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
    or
    auth.email() in ('barannnbozkurttb.b@gmail.com', 'barannnnbozkurttb.b@gmail.com')
  );

create policy "Admins can update reports"
  on reports for update
  using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
      and profiles.role = 'admin'
    )
    or
    auth.email() in ('barannnbozkurttb.b@gmail.com', 'barannnnbozkurttb.b@gmail.com')
  );
