export const SEO_PRIORITY_ARTICLES = [
    {
        slug: "kuantum-fiziginin-baslangici-kara-cisim-isimasi-1766099948990",
        title: "Siyah Cisim Işıması Nedir?",
        description: "Kara cisim ışıması, morötesi felaket ve Planck'ın kuantum fikri.",
        keywords: ["siyah cisim ışıması", "kara cisim ışıması", "morötesi felaket"],
        metadataTitle: "Siyah Cisim Işıması Nedir? Formülü ve Morötesi Felaket",
        metadataDescription: "Siyah cisim ışıması nedir? Kara cisim ışıması, Wien yasası, morötesi felaket ve Planck'ın kuantum fikrini örneklerle öğren.",
        h1: "Siyah Cisim Işıması Nedir? Kara Cisim ve Morötesi Felaket",
        expandedKeywords: ["siyah cisim ışıması", "kara cisim ışıması", "morötesi felaket", "Planck sabiti", "kuantum fiziği", "Wien yasası", "Planck yasası"],
        summaryTitle: "Siyah cisim ışıması nedir?",
        summary: "Siyah cisim ışıması, üzerine düşen tüm ışığı soğuran ideal bir cismin sıcaklığına bağlı olarak yaydığı elektromanyetik ışımadır. Klasik fizik bu ışımayı açıklamakta zorlanınca Planck enerjinin kesikli paketler halinde yayıldığını öne sürdü ve kuantum fiziğinin kapısı açıldı.",
        formulaTitle: "Temel fikir ve formül",
        formula: "E = h f ve lambda_max T = b",
        formulaExplanation: "Planck'a göre ışık enerjisi frekansla orantılı paketler halinde yayılır. Wien yasası ise sıcak cisimlerin en güçlü ışımayı yaptığı dalga boyunun sıcaklık arttıkça kısaldığını gösterir.",
        exampleTitle: "Günlük örnek",
        example: "Isınan bir metalin önce kırmızı, sonra daha açık renkte parlaması siyah cisim ışımasına yakın bir davranıştır; sıcaklık arttıkça yayılan ışığın baskın dalga boyu kısalır.",
        subtopics: ["Kara cisim modeli", "Planck sabiti", "Wien yasası", "Morötesi felaket"],
        questions: [
            {
                question: "Kara cisim ile siyah cisim aynı şey mi?",
                answer: "Evet. Türkçede iki kullanım da aynı fiziksel modeli anlatır: üzerine gelen ışığı ideal olarak soğuran ve sıcaklığına göre ışınım yapan cisim.",
            },
            {
                question: "Morötesi felaket nedir?",
                answer: "Klasik fiziğin kısa dalga boylarında sonsuz enerji öngörmesi problemidir. Gerçek deneyler bunu göstermediği için Planck'ın kuantum fikri ortaya çıktı.",
            },
            {
                question: "Siyah cisim ışıması neden önemlidir?",
                answer: "Kuantum fiziğinin doğuşuna giden en önemli deneysel problemlerden biridir ve yıldızların sıcaklığını, ışık rengini ve termal ışımayı anlamamıza yardım eder.",
            },
        ],
        relatedQueries: ["Planck sabiti nedir?", "Wien yasası nedir?", "Kuantum fiziği nasıl başladı?"],
        relatedSlugs: [
            "klasik-fizige-vurulan-ikinci-darbe-fotoelektrik-olay-1766621600619",
            "tanri-zar-atar-mi-1767761695497",
            "fizikte-ritmi-yakalamak-basit-harmonik-hareket-nedir-mk9qw6u9gcj",
        ],
        termLinks: [{ label: "Planck sabiti", href: "/sozluk/planck-sabiti" }],
    },
    {
        slug: "fizikte-ritmi-yakalamak-basit-harmonik-hareket-nedir-mk9qw6u9gcj",
        title: "Periyodik Hareket Nedir?",
        description: "Basit harmonik hareket, periyot, frekans ve salınım örnekleri.",
        keywords: ["periyodik hareket nedir", "basit harmonik hareket", "salınım"],
        metadataTitle: "Periyodik Hareket Nedir? Basit Harmonik Hareket Formülleri",
        metadataDescription: "Periyodik hareket nedir? Basit harmonik hareket formülleri, periyot, frekans, salınım ve yay-sarkaç örneklerini sade şekilde öğren.",
        h1: "Periyodik Hareket Nedir? Basit Harmonik Hareket Formülleri",
        expandedKeywords: ["periyodik hareket nedir", "basit harmonik hareket nedir", "salınım", "periyot", "frekans", "BHH"],
        summaryTitle: "Periyodik hareket nedir?",
        summary: "Periyodik hareket, belirli zaman aralıklarında kendini tekrar eden harekettir. Basit harmonik hareket ise denge noktasına doğru geri çağırıcı kuvvetin uzaklıkla orantılı olduğu özel bir periyodik harekettir; sarkaç ve yay-kütle sistemi bunun en bilinen örnekleridir.",
        formulaTitle: "BHH için temel formüller",
        formula: "x(t) = A cos(omega t + phi), T = 2pi sqrt(m/k), f = 1/T",
        formulaExplanation: "x(t) cismin konumunu, A genliği, omega açısal frekansı, T periyodu ve f frekansı gösterir. Yay-kütle sisteminde periyot kütle ve yay sabitine bağlıdır.",
        exampleTitle: "Yay-kütle örneği",
        example: "Bir yay ucundaki kütleyi çekip bıraktığında cisim denge noktasının iki yanında gidip gelir. Sürtünme küçükse hareket yaklaşık basit harmonik harekettir.",
        subtopics: ["Periyot ve frekans", "Genlik", "Yay-kütle sistemi", "Sarkaç hareketi"],
        questions: [
            {
                question: "Basit harmonik hareket nedir?",
                answer: "Denge noktasından uzaklaşan bir cismin, uzaklığıyla orantılı bir geri çağırıcı kuvvetle tekrar dengeye yöneldiği düzenli salınım hareketidir.",
            },
            {
                question: "Periyodik hareket ile basit harmonik hareket aynı mı?",
                answer: "Hayır. Her basit harmonik hareket periyodiktir ama her periyodik hareket basit harmonik hareket değildir.",
            },
            {
                question: "Periyot ve frekans neyi anlatır?",
                answer: "Periyot bir tam hareketin süresidir. Frekans ise bir saniyede kaç tekrar olduğunu gösterir.",
            },
        ],
        relatedQueries: ["Basit harmonik hareket formülleri", "Periyot ve frekans farkı", "Sarkaç hareketi nedir?"],
        relatedSlugs: [
            "sessiz-bir-varsayim-yercekimi-1766294899545",
            "kuantum-fiziginin-baslangici-kara-cisim-isimasi-1766099948990",
            "entropi-nedir-evrenin-sonu-nasil-gelecek-1767534266662",
        ],
        termLinks: [{ label: "Harmonik hareket", href: "/sozluk/harmonik-hareket" }],
    },
    {
        slug: "entropi-nedir-evrenin-sonu-nasil-gelecek-1767534266662",
        title: "Entropi Nedir?",
        description: "Entropi ne demek, yüksek entropi ve termodinamikte entropi artışı.",
        keywords: ["entropi nedir", "entropi ne demek", "yüksek entropi"],
        metadataTitle: "Entropi Nedir? Formülü, Anlamı ve Günlük Örnekler",
        metadataDescription: "Entropi nedir, ne demek? Entropi formülü, yüksek entropi, termodinamiğin ikinci yasası ve günlük hayat örneklerini sade şekilde öğren.",
        h1: "Entropi Nedir? Formülü, Anlamı ve Günlük Hayattan Örnekler",
        expandedKeywords: ["entropi nedir", "entropi ne demek", "yüksek entropi nedir", "termodinamik", "düzensizlik", "ısıl ölüm"],
        summaryTitle: "Entropi nedir?",
        summary: "Entropi, bir sistemde enerjinin ne kadar dağılmış olduğunu ve doğal süreçlerin hangi yönde ilerlediğini anlatan termodinamik büyüklüktür. Günlük dilde düzensizlik benzetmesi işe yarar, ama entropi asıl olarak enerjinin kullanılabilirliğinin azalmasıyla ilgilidir.",
        formulaTitle: "Entropi için iki temel ifade",
        formula: "Delta S = Q_rev / T ve S = k ln Omega",
        formulaExplanation: "Delta S tersinir ısı alışverişinde entropi değişimini verir. Boltzmann ifadesi ise entropiyi bir sistemin mümkün mikroskobik durum sayısıyla ilişkilendirir.",
        exampleTitle: "Günlük örnek",
        example: "Sıcak kahvenin odada soğuması, ısının kendiliğinden daha geniş bir çevreye yayılmasıdır. Enerji daha dağılmış hale geldiği için toplam entropi artar.",
        subtopics: ["Termodinamiğin ikinci yasası", "Yüksek entropi", "Isıl ölüm", "Boltzmann yorumu"],
        questions: [
            {
                question: "Entropi ne demek?",
                answer: "Entropi, enerjinin sistem içinde yayılma ve daha az kullanılabilir hale gelme eğilimini ölçen fiziksel büyüklüktür.",
            },
            {
                question: "Yüksek entropi nedir?",
                answer: "Yüksek entropi, enerjinin daha dağılmış olduğu ve sistemden düzenli iş çıkarmanın daha zorlaştığı durumu anlatır.",
            },
            {
                question: "Entropi neden artar?",
                answer: "Kapalı sistemlerde doğal süreçler genellikle enerjiyi daha dağınık hale getirir. Bu yüzden toplam entropi zamanla artma eğilimindedir.",
            },
        ],
        relatedQueries: ["Termodinamiğin ikinci yasası", "Isıl ölüm nedir?", "Düşük entropi nedir?"],
        relatedSlugs: [
            "kuantum-fiziginin-baslangici-kara-cisim-isimasi-1766099948990",
            "fizikte-ritmi-yakalamak-basit-harmonik-hareket-nedir-mk9qw6u9gcj",
            "parcacik-fizigine-giris-evrenin-perde-arkasi-1767186788291",
        ],
        termLinks: [{ label: "Entropi", href: "/sozluk/entropi" }],
    },
    {
        slug: "karanlik-madde-nedir-nasil-gorunur",
        title: "Karanlık Madde Nedir?",
        description: "Karanlık madde kanıtları, galaksi dönüş eğrileri ve görünmeyen kütle fikri.",
        keywords: ["karanlık madde nedir", "dark matter nedir", "karanlık madde kanıtları"],
        metadataTitle: "Karanlık Madde Nedir? Kanıtları ve Nasıl Görünür?",
        metadataDescription: "Karanlık madde nedir? Galaksi dönüş eğrileri, kütle çekim merceklenmesi ve evrendeki görünmeyen madde kanıtlarını sade şekilde öğren.",
        h1: "Karanlık Madde Nedir? Kanıtları ve Nasıl Görünür?",
        expandedKeywords: ["karanlık madde nedir", "dark matter", "galaksi dönüş eğrisi", "kütle çekim merceklenmesi", "görünmeyen madde", "kozmoloji"],
        summaryTitle: "Karanlık madde nedir?",
        summary: "Karanlık madde ışık yaymayan, soğurmayan ve yansıtmayan; varlığını ise kütle çekim etkileriyle anladığımız madde türüdür. Galaksilerin beklenenden hızlı dönmesi ve kütle çekim merceklenmesi, evrende gördüğümüz maddeden daha fazla kütle olduğunu gösterir.",
        formulaTitle: "Galaksi dönüş fikri",
        formula: "v = sqrt(G M(r) / r)",
        formulaExplanation: "Bir yıldızın yörünge hızı, bulunduğu yarıçap içindeki toplam kütleye bağlıdır. Gözlenen hızlar görünür maddeyle açıklanamayınca ek kütle, yani karanlık madde fikri güçlenir.",
        exampleTitle: "Gözlemsel örnek",
        example: "Bir galaksinin dış bölgelerindeki yıldızlar beklenenden yavaşlamak yerine hızlı dönmeye devam ediyorsa, o bölgede görünmeyen ek kütle olduğu düşünülür.",
        subtopics: ["Galaksi dönüş eğrileri", "Kütle çekim merceklenmesi", "Karanlık madde adayları", "Karanlık enerji farkı"],
        questions: [
            {
                question: "Karanlık madde neden görünmez?",
                answer: "Elektromanyetik ışıkla güçlü etkileşmediği için teleskoplarla doğrudan görülmez; etkisi kütle çekimi üzerinden ölçülür.",
            },
            {
                question: "Karanlık madde kanıtlandı mı?",
                answer: "Doğrudan parçacığı yakalanmadı, ancak galaksi dönüşleri, merceklenme ve kozmik mikrodalga arka planı gibi bağımsız gözlemler güçlü dolaylı kanıtlar sunar.",
            },
            {
                question: "Karanlık madde ile karanlık enerji aynı mı?",
                answer: "Hayır. Karanlık madde galaksi ve kümelerin kütle çekim davranışını açıklar; karanlık enerji evrenin hızlanan genişlemesiyle ilişkilidir.",
            },
        ],
        relatedQueries: ["Karanlık madde kanıtları", "Karanlık enerji nedir?", "Galaksi dönüş eğrisi nedir?"],
        relatedSlugs: [
            "fisiltidan-cigliga-gorunmez-iplikler-1766409396465",
            "kara-delige-dusersek-ne-olur-1766107168421",
            "parcacik-fizigine-giris-evrenin-perde-arkasi-1767186788291",
        ],
        termLinks: [{ label: "Karanlık madde", href: "/sozluk/karanlik-madde" }],
    },
    {
        slug: "klasik-fizige-vurulan-ikinci-darbe-fotoelektrik-olay-1766621600619",
        title: "Fotoelektrik Olay Nedir?",
        description: "Fotoelektrik olay, Einstein'ın ışık kuantumu fikri ve eşik frekansı.",
        keywords: ["fotoelektrik olay nedir", "fotoelektrik formülü", "eşik frekansı"],
        metadataTitle: "Fotoelektrik Olay Nedir? Formülü ve Einstein Açıklaması",
        metadataDescription: "Fotoelektrik olay nedir? Einstein'ın ışık kuantumu açıklaması, eşik frekansı, iş fonksiyonu ve fotoelektrik formülünü örneklerle öğren.",
        h1: "Fotoelektrik Olay Nedir? Formülü ve Einstein Açıklaması",
        expandedKeywords: ["fotoelektrik olay nedir", "fotoelektrik formülü", "Einstein fotoelektrik", "eşik frekansı", "iş fonksiyonu", "ışık kuantumu"],
        summaryTitle: "Fotoelektrik olay nedir?",
        summary: "Fotoelektrik olay, yeterince yüksek frekanslı ışığın metal yüzeyden elektron koparmasıdır. Einstein bu olayı ışığın enerjisinin foton paketleri halinde taşındığını söyleyerek açıkladı ve kuantum fiziğinin deneysel temel taşlarından birini oluşturdu.",
        formulaTitle: "Fotoelektrik denklem",
        formula: "K_max = h f - phi",
        formulaExplanation: "Fotonun enerjisi h f kadardır. Metalden elektron koparmak için gereken enerji phi ile gösterilir; kalan enerji elektronun maksimum kinetik enerjisine dönüşür.",
        exampleTitle: "Eşik frekansı örneği",
        example: "Işığın şiddetini artırmak elektron koparmaya yetmeyebilir. Frekans eşik değerin altındaysa foton başına enerji yetersiz kalır ve elektron kopmaz.",
        subtopics: ["Foton enerjisi", "Eşik frekansı", "İş fonksiyonu", "Klasik fiziğin sınırı"],
        questions: [
            {
                question: "Fotoelektrik olay neyi kanıtlar?",
                answer: "Işığın yalnızca dalga gibi değil, enerji paketleri yani fotonlar gibi de davrandığını gösterir.",
            },
            {
                question: "Işık şiddeti artınca neden her zaman elektron kopmaz?",
                answer: "Elektron kopması için foton başına enerji yeterli olmalıdır. Frekans eşik değerin altındaysa şiddet artsa bile tek foton elektronu koparamaz.",
            },
            {
                question: "Fotoelektrik olayın günlük kullanımı var mı?",
                answer: "Evet. Işık sensörleri, güneş pilleri ve bazı görüntüleme teknolojileri fotoelektrik etkinin kuantum mantığına dayanır.",
            },
        ],
        relatedQueries: ["Eşik frekansı nedir?", "Foton enerjisi formülü", "Einstein fotoelektrik olay"],
        relatedSlugs: [
            "kuantum-fiziginin-baslangici-kara-cisim-isimasi-1766099948990",
            "tanri-zar-atar-mi-1767761695497",
            "parcacik-fizigine-giris-evrenin-perde-arkasi-1767186788291",
        ],
        termLinks: [{ label: "Fotoelektrik olay", href: "/sozluk/fotoelektrik-olay" }],
    },
    {
        slug: "kara-delige-dusersek-ne-olur-1766107168421",
        title: "Kara Deliğe Düşersek Ne Olur?",
        description: "Kara deliğe düşme, olay ufku, gelgit kuvvetleri ve spagettileşme.",
        keywords: ["kara deliğe düşersek ne olur", "kara delik nedir", "olay ufku"],
        metadataTitle: "Kara Deliğe Düşersek Ne Olur? Olay Ufku ve Spagettileşme",
        metadataDescription: "Kara deliğe düşersek ne olur? Olay ufku, Schwarzschild yarıçapı, gelgit kuvvetleri ve spagettileşmeyi sade örneklerle öğren.",
        h1: "Kara Deliğe Düşersek Ne Olur? Olay Ufku ve Spagettileşme",
        expandedKeywords: ["kara deliğe düşersek ne olur", "kara delik nedir", "olay ufku", "Schwarzschild yarıçapı", "spagettileşme", "gelgit kuvveti"],
        summaryTitle: "Kara deliğe düşersek ne olur?",
        summary: "Kara deliğe yaklaşan bir cisim önce güçlü gelgit kuvvetleriyle uzayıp sıkışabilir. Olay ufku geçildikten sonra dışarıya ışık bile dönemediği için geri kaçış mümkün olmaz; dış gözlemci ise düşüşü giderek yavaşlıyor gibi görür.",
        formulaTitle: "Olay ufku yarıçapı",
        formula: "r_s = 2 G M / c^2",
        formulaExplanation: "Schwarzschild yarıçapı, dönmeyen ve yüksüz bir kara deliğin olay ufkunun yaklaşık yarıçapını verir. Kütle arttıkça olay ufku da büyür.",
        exampleTitle: "Dışarıdan ve içeriden bakış",
        example: "Düşen kişi kendi saatinde olay ufkunu sonlu sürede geçer. Uzaktaki gözlemci ise ışığın kızıla kayması nedeniyle kişiyi ufka yaklaşırken donmuş gibi algılar.",
        subtopics: ["Olay ufku", "Gelgit kuvvetleri", "Schwarzschild yarıçapı", "Zaman genişlemesi"],
        questions: [
            {
                question: "Olay ufkunu geçince geri dönülebilir mi?",
                answer: "Hayır. Olay ufkunun içinde kaçış hızı ışık hızını aştığı için bilinen fizik içinde dışarıya bilgi veya madde dönemez.",
            },
            {
                question: "Spagettileşme nedir?",
                answer: "Kara deliğin yakınında cismin farklı uçlarına uygulanan kütle çekim farkı çok büyür; cisim bir yönde uzayıp diğer yönde sıkışır.",
            },
            {
                question: "Kara delikler her şeyi yutar mı?",
                answer: "Hayır. Uzaktaki cisimler kara deliğin kütle çekim alanında normal yörüngelerde kalabilir; tehlike çok yakına girildiğinde başlar.",
            },
        ],
        relatedQueries: ["Olay ufku nedir?", "Schwarzschild yarıçapı", "Spagettileşme nedir?"],
        relatedSlugs: [
            "saatler-yalan-soyler-evren-dev-bir-zaman-makinesidir-1766154361647",
            "sessiz-bir-varsayim-yercekimi-1766294899545",
            "karanlik-madde-nedir-nasil-gorunur",
        ],
        termLinks: [{ label: "Karadelik", href: "/sozluk/karadelik" }],
    },
    {
        slug: "parcacik-fizigine-giris-evrenin-perde-arkasi-1767186788291",
        title: "Parçacık Fiziği Nedir?",
        description: "Parçacık fiziğine giriş, temel parçacıklar, kuvvet taşıyıcıları ve Standart Model.",
        keywords: ["parçacık fiziği nedir", "standart model nedir", "temel parçacıklar"],
        metadataTitle: "Parçacık Fiziği Nedir? Standart Model ve Temel Parçacıklar",
        metadataDescription: "Parçacık fiziği nedir? Standart Model, kuarklar, leptonlar, bozonlar ve temel kuvvetleri sade bir giriş rehberiyle öğren.",
        h1: "Parçacık Fiziği Nedir? Standart Model ve Temel Parçacıklar",
        expandedKeywords: ["parçacık fiziği nedir", "Standart Model", "kuark", "lepton", "bozon", "Higgs bozonu", "temel kuvvetler"],
        summaryTitle: "Parçacık fiziği nedir?",
        summary: "Parçacık fiziği, maddenin ve kuvvetlerin en temel yapı taşlarını inceleyen fizik dalıdır. Standart Model; kuarkları, leptonları, kuvvet taşıyıcı bozonları ve Higgs alanını tek bir çerçevede açıklar.",
        formulaTitle: "Enerji-kütle ilişkisi",
        formula: "E^2 = (p c)^2 + (m c^2)^2",
        formulaExplanation: "Parçacık fiziğinde enerji yalnızca kütleden gelmez; momentum da toplam enerjiye katkı verir. Bu ilişki yüksek enerjili çarpışmaları anlamak için temel araçlardan biridir.",
        exampleTitle: "Çarpıştırıcı örneği",
        example: "Parçacık hızlandırıcılarında protonlar yüksek enerjiyle çarpıştırılır. Ortaya çıkan izler, kısa ömürlü parçacıkların hangi temel etkileşimlerle oluştuğunu gösterir.",
        subtopics: ["Kuarklar ve leptonlar", "Bozonlar", "Higgs alanı", "Standart Model sınırları"],
        questions: [
            {
                question: "Standart Model neyi açıklar?",
                answer: "Bilinen temel parçacıkları ve elektromanyetik, zayıf, güçlü etkileşimleri açıklar; kütle çekimi ise bu modelin dışında kalır.",
            },
            {
                question: "Kuark ve lepton farkı nedir?",
                answer: "Kuarklar proton ve nötron gibi hadronları oluşturur. Leptonlar ise elektron ve nötrino gibi parçacıkları kapsar.",
            },
            {
                question: "Higgs bozonu neden önemlidir?",
                answer: "Higgs alanıyla ilişkili olduğu için parçacıkların kütle kazanma mekanizmasını anlamamızda kilit rol oynar.",
            },
        ],
        relatedQueries: ["Standart Model nedir?", "Higgs bozonu nedir?", "Kuark nedir?"],
        relatedSlugs: [
            "karanlik-madde-nedir-nasil-gorunur",
            "klasik-fizige-vurulan-ikinci-darbe-fotoelektrik-olay-1766621600619",
            "tanri-zar-atar-mi-1767761695497",
        ],
        termLinks: [{ label: "Standart Model", href: "/sozluk/standart-model" }],
    },
    {
        slug: "evrenin-derinliklerine-bakis-james-webb-uzay-teleskobu",
        title: "James Webb Uzay Teleskobu Nedir?",
        description: "JWST, kızılötesi gözlem, erken evren ve altın aynaların bilimsel amacı.",
        keywords: ["James Webb uzay teleskobu nedir", "JWST nedir", "James Webb ne işe yarar"],
        metadataTitle: "James Webb Uzay Teleskobu Nedir? Ne İşe Yarar?",
        metadataDescription: "James Webb Uzay Teleskobu nedir? JWST'nin kızılötesi gözlem gücü, erken evren, ötegezegen atmosferleri ve altın aynalarını sade şekilde öğren.",
        h1: "James Webb Uzay Teleskobu Nedir? Ne İşe Yarar?",
        expandedKeywords: ["James Webb uzay teleskobu nedir", "JWST", "kızılötesi teleskop", "erken evren", "ötegezegen atmosferi", "kırmızıya kayma"],
        summaryTitle: "James Webb Uzay Teleskobu nedir?",
        summary: "James Webb Uzay Teleskobu, evreni özellikle kızılötesi ışıkta gözlemleyen güçlü bir uzay teleskobudur. Toz bulutlarının arkasını, erken galaksileri ve ötegezegen atmosferlerini inceleyerek evrenin geçmişine daha ayrıntılı bakmamızı sağlar.",
        formulaTitle: "Kırmızıya kayma fikri",
        formula: "1 + z = lambda_obs / lambda_emit",
        formulaExplanation: "Uzak galaksilerden gelen ışığın dalga boyu evrenin genişlemesiyle uzar. James Webb kızılötesinde güçlü olduğu için bu uzak ve kırmızıya kaymış ışığı yakalayabilir.",
        exampleTitle: "Neden kızılötesi?",
        example: "Bir yıldız doğum bölgesinde görünür ışık toz tarafından engellenebilir. Kızılötesi ışık ise bu tozun içinden daha kolay geçer ve Webb'in saklı yapıları görmesini sağlar.",
        subtopics: ["Kızılötesi gözlem", "Erken galaksiler", "Ötegezegen atmosferleri", "Kırmızıya kayma"],
        questions: [
            {
                question: "James Webb Hubble'ın yerine mi geçti?",
                answer: "Tam olarak hayır. Hubble ve Webb farklı dalga boylarında güçlüdür; Webb özellikle kızılötesi gözlemler için tasarlanmıştır.",
            },
            {
                question: "James Webb neden altın kaplı aynalar kullanır?",
                answer: "Altın, kızılötesi ışığı çok iyi yansıttığı için Webb'in hedeflediği dalga boylarında verimi artırır.",
            },
            {
                question: "JWST geçmişe nasıl bakıyor?",
                answer: "Işığın yol alması zaman aldığı için çok uzak galaksilerden gelen ışık, o galaksilerin milyarlarca yıl önceki halini gösterir.",
            },
        ],
        relatedQueries: ["JWST ne işe yarar?", "Kızılötesi teleskop nedir?", "Kırmızıya kayma nedir?"],
        relatedSlugs: [
            "saatler-yalan-soyler-evren-dev-bir-zaman-makinesidir-1766154361647",
            "karanlik-madde-nedir-nasil-gorunur",
            "kara-delige-dusersek-ne-olur-1766107168421",
        ],
        termLinks: [{ label: "Kızıla kayma", href: "/sozluk/kizila-kayma" }],
    },
] as const;

export const SEO_PRIORITY_SLUGS = SEO_PRIORITY_ARTICLES.map((article) => article.slug);

export const SEO_PRIORITY_SLUG_SET = new Set<string>(SEO_PRIORITY_SLUGS);

export type SeoIntentArticle = (typeof SEO_PRIORITY_ARTICLES)[number];

export function getSeoIntentForSlug(slug: string | null | undefined) {
    return SEO_PRIORITY_ARTICLES.find((article) => article.slug === slug);
}
