-- Phase 1 of the CSP nonce/hash migration: persist deduplicated report-only
-- violations while the enforced policy still keeps unsafe-inline as a fallback.

BEGIN;

CREATE TABLE IF NOT EXISTS public.csp_violation_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_day date NOT NULL DEFAULT CURRENT_DATE,
    fingerprint text NOT NULL,
    document_url text,
    violated_directive text,
    blocked_url text,
    source_file text,
    line_number integer,
    column_number integer,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (fingerprint, report_day)
);

ALTER TABLE public.csp_violation_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.csp_violation_events FROM anon, authenticated;
GRANT SELECT, INSERT ON public.csp_violation_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.csp_violation_events_id_seq TO service_role;

CREATE INDEX IF NOT EXISTS csp_violation_events_created_at_idx
    ON public.csp_violation_events (created_at DESC);

COMMIT;
